# Generated by Django 6.0.3 on 2026-03-25 05:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_usermodel_name_usermodel_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='profileImg',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_image'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='resume',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
