# Generated by Django 6.0.3 on 2026-03-28 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_usermodel_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='location',
        ),
    ]
