# Generated by Django 6.0.3 on 2026-03-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_remove_usermodel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
