# Generated by Django 6.0.3 on 2026-03-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_usermodel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='portfolio',
            field=models.URLField(blank=True, null=True),
        ),
    ]
