# Generated by Django 6.0.3 on 2026-03-19 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='resume',
        ),
    ]
